name: Deplotment exercise 1
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v3
            - name: install depednds 
              run: npm ci
            - name:  lint
              run: npm run lint  

    testing:
        needs: lint
        runs-on: ubuntu-latest      
        steps:
            - name: get code
              uses: actions/checkout@v3
            - name: install depednds 
              run: npm ci 
            - name: test code 
              run: npm run test                    
    deploy:
        needs: testing  
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v3
            - name: install depednds 
              run: npm ci 


            - name: build code 
              run: npm run build
            - name: Deploy code
              run: echo  "deploying... the code "

